export const BountyJsondata = [
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
    {
        logo: "logo",
        companyName: "companyName",
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
        price: 1389,
    },
]