export const ContributorJsonData = [
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
    {
        logo: "logo",
        contributorName: "User Name",
        reputation: 1640,
        description: "Sovereign cloud nation. Building a community of like-minded people creating a nation on the cloud. #WeAreNATION",
    },
]